spring:
  profiles:
    active: ${APP_PROFILE:test}
  security:
    oauth2:
      client:
        client-id: ${CLIENT_ID:daniellucas}
        client-secret: ${CLIENT_SECRET:daniellucas123}

jwt:
  secret: ${JWT_SECRET:MY-JWT-SECRET}
  duration: ${JWT_DURATION:86400}
